### ISSUE TITLE
MonthSelector does not disappear on button clicked

### ISSUE THREAD

**Issue by romainreignier** [AsteroidOS/asteroid-calendar#2]
In the calendar/agenda app, in the month selector, a click on the button at the bottom does not return in the previous view. So it seems that the `root.pop()` has no effect:

https://github.com/AsteroidOS/asteroid-calendar/blob/master/MonthSelector.qml#L118

But note that the selected date is taken into account when returning to the previous view with a "left-to-right" swipe after touching the button (no effect if the button is not touched).

**Comment by FlorentRevest** [comment]
Thanks, closed by b7cd65c81aaaea5552502b5e8ac35de37b1eb7ea
