### ISSUE TITLE
/* App asteroid-calendar (AGENDA) not start up */ 

### ISSUE THREAD

**Issue by Caballlero** [AsteroidOS/asteroid-calendar#6]
- Only show a white screen. Just notifying....

**Comment by FlorentRevest** [comment]
Can you include the results of the journalctl --no-pager command (ran through ssh root@192.168.2.15 or adb shell depending on the date of your build)

**Comment by Caballlero** [comment]
[journalctl --no-pager.zip](https://github.com/AsteroidOS/asteroid-calendar/files/1002860/journalctl.--no-pager.zip)

**Comment by Caballlero** [comment]
The calendar (AGENDA) apps was Fixed by reboot the watch. After flash...  now everything  good.

**Comment by FlorentRevest** [comment]
https://github.com/AsteroidOS/meta-asteroid/commit/68a3f5b57b375dfda21106d860e88440ba2041b9 may help. Please update when you can on whether this bug happens again or not on newer build.

**Comment by Caballlero** [comment]
I could not test ,because > #23

**Comment by Caballlero** [comment]
- Fixed in  >> 20-May-2017 22:12   = )
